---
- name: Verify
  hosts: apic
  gather_facts: no

  tasks:
    - name: Load Defaults
      ansible.builtin.include_role:
        name: cisco.aac.apic_common
        vars_from: apic_defaults.yaml
        public: yes

    - name: Run Tests
      block:
        - name: Run Tests
          vars:
            skip_non_idempotent_tasks: True
            test_report_name: "{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}"
          ansible.builtin.include_role:
            name: cisco.aac.test_apic_deploy

      always:
        - name: Create Common Test Results Directory
          ansible.builtin.file:
            path: "../../../../../test_results/lab/{{ inventory_hostname }}/apic_deploy/{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}/"
            state: directory
          register: results_dir

        - name: Copy Test Results
          ansible.posix.synchronize:
            src: '{{ test_results_folder | default(aac_defaults.aac.test_results_folder) }}'
            dest: '{{ results_dir.path }}'
            dirs: yes
            recursive: no
