---
- name: 'RENDER TEST : MSO Common'
  cisco.aac.template_local:
    src: 'mso_common.robot'
    dest: "{{ rendered_folder | default(aac_defaults.aac.rendered_folder) }}{{ test_folder | default('tests') }}/mso_common.resource"
    lstrip_blocks: yes
