---
- name: Converge
  hosts: localhost
  gather_facts: no
  vars:
    yaml_paths:
      [
        '../../../../apic_deploy/molecule/01_standard/data/host_vars/apic1',
        '../../../../apic_deploy/molecule/02_scale/data/host_vars/apic1',
      ]

  tasks:
    - name: APIC Validate
      ansible.builtin.include_role:
        name: cisco.aac.apic_validate
      loop: '{{ yaml_paths }}'
      loop_control:
        loop_var: yaml_path
