---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      connection: local
platforms:
  - name: mso1
provisioner:
  name: ansible
  log: True
  env:
    ANSIBLE_COLLECTIONS_PATHS: '~/.ansible/collections:../../../../'
  playbooks:
    converge: ../resources/playbooks/playbook.yaml
verifier:
  name: ansible
  enabled: False
scenario:
  test_sequence:
    - converge
