---
- name: 'RENDER : {{ taskprefix | default() }}{{ item[0].name }}'
  cisco.aac.template_local:
    src: '{{ item[0].folder }}/{{ item[0].template }}.j2'
    dest: '{{ rendered_folder | default(aac_defaults.aac.rendered_folder) }}config/{{ item[0].folder }}/{{ item[2] | default() }}{{ item[1] | default() | string }}/{{ item[0].template }}.json'
    lstrip_blocks: yes
  register: render_result
  tags: [print_action]
