---
- name: 'CONFIGURE : {{ taskprefix | default() }}{{ item[0].name }}'
  aci_rest:
    hostname: '{{ apic_host }}'
    username: '{{ apic_username }}'
    password: '{{ apic_password | default(omit) }}'
    private_key: '{{ apic_private_key | default(omit) }}'
    use_proxy: '{{ apic_use_proxy | default(defaults.aci.apic_use_proxy) }}'
    validate_certs: '{{ apic_validate_certs | default(defaults.aci.apic_validate_certs) }}'
    path: /api/mo/uni.json
    method: post
    src: '{{ rendered_folder | default(aac_defaults.aac.rendered_folder) }}config/{{ item[0].folder }}/{{ item[2] | default() }}{{ item[1] | default() | string }}/{{ item[0].template }}.json'
  register: configure_result
  changed_when: configure_result.imdata | default() != []
  retries: 3
  delay: 10
  until: configure_result is succeeded
  tags: [print_action]
