---
- name: Snapshot Tasks
  vars:
    aci_common: &aci_common
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password | default(omit) }}'
      private_key: '{{ apic_private_key | default(omit) }}'
      use_proxy: '{{ apic_use_proxy | default(defaults.aci.apic_use_proxy) }}'
      validate_certs: '{{ apic_validate_certs | default(defaults.aci.apic_validate_certs) }}'

  block:
    - name: Load Variables
      ansible.builtin.include_role:
        name: cisco.aac.apic_common
        vars_from: apic_defaults.yaml
        public: yes

    - name: Create Snapshot
      aci_config_snapshot:
        <<: *aci_common
        export_policy: "{{ apic.bootstrap.snapshot_policy | default('AAC-SNAPSHOTS') }}"
        description: "{{ lookup('env', 'ACI_SNAPSHOT_DESC') | default() }}"
        max_count: 10
      register: result
      retries: 2
      delay: 3
      until: result is succeeded
      tags: [print_action]
